### ISSUE TITLE
Failed to load or install JlrsCore package on Julia 1.10.2

### ISSUE THREAD

**Issue by mkitti** [Taaitaaiger/RustFFT.jl#8]
I am having the following issue with Julia 1.10.2 and RustFFT:

```
RustFFT [b7f167ac-9de6-40dd-9818-ec636999de39]

Failed to precompile RustFFT [b7f167ac-9de6-40dd-9818-ec636999de39] to "/home/mkitti/.julia/compiled/v1.10/RustFFT/jl_PbIOXJ".
Failed to load or install JlrsCore package
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Ref<Value>', /opt/x86_64-linux-musl/registry/src/index.crates.io-6f17d22bba15001f/jlrs-0.19.1/src/data/managed/mod.rs:409:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: jlrs::data::managed::Managed::print_error
   4: jlrs::init_jlrs
   5: jlrs::ccall::CCall::init_jlrs
   6: rustfft_jl_init
   7: <unknown>
   8: <unknown>
   9: _jl_invoke
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:2894:23
  10: ijl_apply_generic
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:3076:12
  11: jl_apply
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/julia.h:1982:12
  12: do_call
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:126:26
  13: eval_value
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:223:16
  14: eval_stmt_value
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:174:23
  15: eval_body
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:617:21
  16: jl_interpret_toplevel_thunk
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:775:21
  17: jl_toplevel_eval_flex
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:934:18
  18: jl_eval_module_expr
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:215:15
  19: jl_toplevel_eval_flex
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:736:27
  20: jl_toplevel_eval_flex
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:877:19
  21: ijl_toplevel_eval_in
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:985:13
  22: eval
             at ././boot.jl:385
  23: japi1_include_string_80984
             at ././loading.jl:2076
  24: _jl_invoke
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:2894:23
  25: ijl_apply_generic
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:3076:12
  26: japi1__include_80992
             at ././loading.jl:2136
  27: julia_include_46402
             at ././Base.jl:495
  28: jfptr_include_46403.1
  29: _jl_invoke
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:2894:23
  30: ijl_apply_generic
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:3076:12
  31: jl_apply
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/julia.h:1982:12
  32: jl_f__call_latest
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/builtins.c:812:23
  33: <unknown>
  34: <unknown>
  35: _jl_invoke
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:2894:23
  36: ijl_apply_generic
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:3076:12
  37: jl_apply
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/julia.h:1982:12
  38: do_call
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:126:26
  39: eval_value
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:223:16
  40: eval_stmt_value
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:174:23
  41: eval_body
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:617:21
  42: jl_interpret_toplevel_thunk
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:775:21
  43: jl_toplevel_eval_flex
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:934:18
  44: jl_eval_module_expr
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:215:15
  45: jl_toplevel_eval_flex
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:736:27
  46: jl_toplevel_eval_flex
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:877:19
  47: ijl_toplevel_eval_in
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:985:13
  48: eval
             at ././boot.jl:385
  49: japi1_include_string_80984
             at ././loading.jl:2076
  50: _jl_invoke
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:2894:23
  51: ijl_apply_generic
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:3076:12
  52: japi1__include_80992
             at ././loading.jl:2136
  53: include
             at ././Base.jl:495
  54: julia_include_package_for_output_81021
             at ././loading.jl:2222
  55: jfptr_include_package_for_output_81022.1
  56: _jl_invoke
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:2894:23
  57: ijl_apply_generic
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:3076:12
  58: jl_apply
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/julia.h:1982:12
  59: do_call
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:126:26
  60: eval_value
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:223:16
  61: eval_stmt_value
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:174:23
  62: eval_body
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:617:21
  63: jl_interpret_toplevel_thunk
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/interpreter.c:775:21
  64: jl_toplevel_eval_flex
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:934:18
  65: jl_toplevel_eval_flex
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:877:19
  66: ijl_toplevel_eval_in
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/toplevel.c:985:13
  67: eval
             at ././boot.jl:385
  68: japi1_include_string_80984
             at ././loading.jl:2076
  69: include_string
             at ././loading.jl:2086
  70: julia_exec_options_82599
             at ././client.jl:316
  71: julia__start_82737
             at ././client.jl:552
  72: jfptr__start_82738.1
  73: _jl_invoke
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:2894:23
  74: ijl_apply_generic
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/gf.c:3076:12
  75: jl_apply
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/julia.h:1982:12
  76: true_main
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/jlapi.c:582:13
  77: jl_repl_entrypoint
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/jlapi.c:731:15
  78: main
             at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/cli/loader_exe.c:58:15
  79: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  80: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  81: <unknown>
             at /workspace/srcdir/glibc-2.17/csu/../sysdeps/x86_64/start.S:123
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[7107] signal (6.-6): Aborted
in expression starting at /home/mkitti/.julia/packages/RustFFT/88FlR/src/Internal.jl:12
pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
raise at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/panic_abort/src/lib.rs:42
unknown function (ip: (nil))
Allocations: 603620 (Pool: 602480; Big: 1140); GC: 
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Types.jl:70
  [2] precompile(ctx::Pkg.Types.Context, pkgs::Vector{…}; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, timing::Bool, _from_loading::Bool, kwargs::@Kwargs{…})
    @ Pkg.API ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/API.jl:1659
  [3] precompile(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::@Kwargs{_from_loading::Bool})
    @ Pkg.API ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/API.jl:159
  [4] precompile
    @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/API.jl:147 [inlined]
  [5] #precompile#114
    @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/API.jl:146 [inlined]
  [6] #invokelatest#2
    @ ./essentials.jl:894 [inlined]
  [7] invokelatest
    @ ./essentials.jl:889 [inlined]
  [8] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1963
  [9] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1812
 [10] #invoke_in_world#3
    @ ./essentials.jl:926 [inlined]
 [11] invoke_in_world
    @ ./essentials.jl:923 [inlined]
 [12] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1803
 [13] macro expansion
    @ ./loading.jl:1790 [inlined]
 [14] macro expansion
    @ ./lock.jl:267 [inlined]
 [15] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1753
 [16] #invoke_in_world#3
    @ ./essentials.jl:926 [inlined]
 [17] invoke_in_world
    @ ./essentials.jl:923 [inlined]
 [18] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1746
Some type information was truncated. Use `show(err)` to see complete types.

```

**Comment by Taaitaaiger** [comment]
Ah, this is stupid of me. I'm pretty sure I forgot to request a rebuild of the JLL after solving the cause of this issue. I need to check if that's the case, I'll try to make some time for that this week, but I might not b able to find time until next week.

**Comment by mkitti** [comment]
If that is all that is required, I can give it a try.

**Comment by Taaitaaiger** [comment]
I just checked, the JLL was built with jlrs 0.19.1...

If you build the JLL with BinaryBuilder it should automatically pick up
0.19.2. Feel free to bump the patch version of rustfft in Yggdrasil, or
build it manually. Please let me know if you run into any problems!

**Comment by kdheepak** [comment]
@Taaitaaiger if you are interested, I have a github workflow for `libcrossterm` that automatically makes a PR to Yggdrasil when I make a release:

https://github.com/kdheepak/libcrossterm/blob/b16c0fee4421223e9ae879decb30123b06a1081c/.github/workflows/cd.yml#L86-L132

**Comment by Taaitaaiger** [comment]
That might be interesting, but that would require me to make dummy releases of rustfft-jl. Fixing this issues required no work at all in that codebase, it was purely a bug in jlrs, and rustfft-jl depends on jlrs in a way that lets it automatically pick up new bugfix-releases. 

I've built the library locally and verified that it precompiles correctly. Building is currently in progress: https://github.com/JuliaPackaging/Yggdrasil/pull/8568

**Comment by Taaitaaiger** [comment]
Problem solved :smile: 

```
(@v1.10) pkg> update
    Updating registry at `~/.julia/registries/General.toml`
   Installed rustfft_jll ─ v0.3.2+0
  Downloaded artifact: rustfft
    Updating `~/.julia/environments/v1.10/Project.toml`
  [54eccfce] ↑ rustfft_jll v0.3.1+0 ⇒ v0.3.2+0
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [54eccfce] ↑ rustfft_jll v0.3.1+0 ⇒ v0.3.2+0
Precompiling project...
  2 dependencies successfully precompiled in 2 seconds. 216 already precompiled.

(@v1.10) pkg> test RustFFT
     Testing RustFFT
      Status `/tmp/jl_kpDvbV/Project.toml`
  [621f4979] AbstractFFTs v1.5.0
  [29be08bc] JlrsCore v0.3.0
  [189a3867] Reexport v1.2.2
  [b7f167ac] RustFFT v0.2.0
  [54eccfce] rustfft_jll v0.3.2+0
  [37e2e46d] LinearAlgebra
  [8dfed614] Test
      Status `/tmp/jl_kpDvbV/Manifest.toml`
  [621f4979] AbstractFFTs v1.5.0
  [692b3bcd] JLLWrappers v1.5.0
  [29be08bc] JlrsCore v0.3.0
  [21216c6a] Preferences v1.4.3
  [189a3867] Reexport v1.2.2
  [b7f167ac] RustFFT v0.2.0
  [946c7259] JlrsLedger_jll v0.1.0+0
  [94ce4f54] Libiconv_jll v1.17.0+0
  [54eccfce] rustfft_jll v0.3.2+0
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [b77e0a4c] InteractiveUtils
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [de0858da] Printf
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [fa267f1f] TOML v1.0.3
  [8dfed614] Test
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.0.5+1
  [4536629a] OpenBLAS_jll v0.3.23+2
  [8e850b90] libblastrampoline_jll v5.8.0+1
Precompiling project...
  7 dependencies successfully precompiled in 7 seconds. 5 already precompiled.
     Testing Running tests...
Test Summary: | Pass  Total  Time
Forward FFT   |    4      4  0.6s
Test Summary: | Pass  Total  Time
Inverse FFT   |    4      4  0.0s
Test Summary: | Pass  Total  Time
Exceptions    |    1      1  0.1s
     Testing RustFFT tests passed
```

**Comment by mkitti** [comment]
xref: https://github.com/JuliaPackaging/Yggdrasil/pull/8568
